### ISSUE TITLE
Slow respons when changing lock state

### ISSUE THREAD

**Issue by frogger11** [GlueHome/homebridge-plugin#10]
Hi,
I installed this plugin yesterday, but there seems to be a problem with app lock state delay from unlocking or lock in the Home-app. The lock icon becomes unresponsive for up to half a minute afterwards a change. I use GLUE Smart Lock 2nd Gen. 
There is no limitation with this lock and this plugin?

If this is a known phenomenon, will this be fixed soon? I have used another plugin but that one stops working on February 15. I have received an email about that from you a couple days ago.

**Comment by frogger11** [comment]
> Hi,
> I installed this plugin yesterday, but there seems to be a problem with app lock state delay from unlocking or lock in the Home-app. The lock icon becomes unresponsive for up to half a minute afterwards a change. I use GLUE Smart Lock 2nd Gen.
> There is no limitation with this lock and this plugin?
> 
> If this is a known phenomenon, will this be fixed soon? I have used another plugin but that one stops working on February 15. I have received an email about that from you a couple days ago.

Still having prov

**Comment by Talento90** [comment]
Hello, first of all thank you for installing our plugin. At this moment we are working on improving GL04 remote operations by making them faster and more reliable. You should see some improvements in the next few days.
