### ISSUE TITLE
Error: Remote operation failed.

### ISSUE THREAD

**Issue by simonepittis74** [GlueHome/homebridge-plugin#12]
Error:
"[GlueHomebridge] Error: Remote operation failed.
    at /usr/lib/node_modules/@gluehome/homebridge-gluehome/src/lock.ts:121:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)"

Node.js v14.16.0
Npm v6.14.11

The HomeBridge plugin fails all times with command fails (you can see in the Error part), the same message you can see in the Glue App, but Lock and Unlock works fine

**Comment by tarek86salmi** [comment]
An getting this error 
ERROR[Hoobs HUb 33F1@Front Door @@Lock Target State] characteristic was supplied illegal value: number 3 exceeded maximum of 1

**Comment by andycb** [comment]
I believe this is now resolved, in the last update. If you continue to see this issue, please reopen.
