### ISSUE TITLE
Question: battery warning at 50%

### ISSUE THREAD

**Issue by frogger11** [GlueHome/homebridge-plugin#13]
Is there any possibility to change the battery warning at 50%? I use rechargeable batteries and have at most achieved about 80% battery left according to the Glue app and the Home app, when it should be fully charged.

Suggestion, I would like to be able to set what the warning should be at, for example, 20%.

**Comment by frogger11** [comment]
Any respons?

**Comment by mariekyle-glue** [comment]
Hi @frogger11 - thank you for the feedback!  You are correct - the platform doesn't currently allow users to configure the battery warning level but we welcome the suggestion and will look into it and see if we are able to add that feature in the future.

**Comment by andycb** [comment]
As this isn't specifically a homebridge request, I'm going to close it here and move it to the internal backlog.
