### ISSUE TITLE
Unkown state when doing manual lock/unlock

### ISSUE THREAD

**Issue by WinkelmannVictor** [GlueHome/homebridge-plugin#22]
**Describe The Bug:**
I own the glue third-generation lock (the packaging says pro version) which means that the knob sensor should work and send unlock/lock updates to homebridge. When doing manual lock/unlock the plugin reports unknown behavior and cant figure out the eventype.

**To Reproduce:**
remote lock or unlock and then manually turn the knob

**Expected behavior:**
hombridge should update the state to locked / unlocked since I have the third version. Not stating unkown.

**Logs:**

```
[3/16/2022, 2:01:58 AM] [@gluehome/homebridge-gluehome] This plugin generated a warning from the characteristic 'Lock Target State': characteristic was supplied illegal value: number 3 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[3/16/2022, 2:01:58 AM] [@gluehome/homebridge-gluehome] Error: 
    at LockTargetState.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at LockTargetState.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2049:14)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1617:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at GlueLockAccessory.getLockTargetState (/homebridge/node_modules/@gluehome/homebridge-gluehome/src/lock.ts:89:5)
    at LockTargetState.emit (node:events:520:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1592:14
    at new Promise (<anonymous>)
    at LockTargetState.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1590:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
```

**Plugin Config:**

```json
{
    "auth": "api-key",
    "apiKey": "secret",
    "_bridge": {
        "username": "secret",
        "port": "removed"
    },
    "platform": "GlueHomebridge"
}
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/47196679/158498049-3c73b3fb-097b-4cd7-b196-701aaa7d6488.png)

**Environment:**

* **Plugin Version**: v0.2.0
* **Homebridge Version**: v1.4.0
* **Node.js Version**: v16.14.0
* **NPM Version**: v8.3.1
* **Operating System**: Ubuntu Bionic Beaver (18.04.6 LTS) in docker

**Comment by kongomannen** [comment]
Exactly the same for me. Please fix this.

**Comment by simonepittis** [comment]
hi Andy,

I try to fix it my self but the result from API it's not the same:
![image](https://user-images.githubusercontent.com/92569194/168990390-5bbfa89b-dc3a-4e31-acc7-edce6cc0bc30.png)
but I see, you have the firmwareversion 2.4...

**Comment by andycb** [comment]
Hi,

Sorry, the actual bug is our end - the user-api that this plugin uses is returning `Unknown` when the instead of `ManualLock` / `ManualUnock` when you use the thumbturn on the lock.

I tested it by pointing the plugin at one of our test environments, where the API is now fixed, and it seemed to work fine with no changes needed in this repo. The lock I used was a random one I had in a cupboard, so may have some exotic firmware on - but I don't think that'll be an issue here. 

I'm aiming to deploy that change out to the production environment next week, when I have some resource from my team to validate it's good. 

I'll report back here when it's done, and hopefully we can resolve this issue then 🙂.

Andy

**Comment by simonepittis** [comment]
Thanks :-)

**Comment by kongomannen** [comment]
Great to hear that you are on it!

**Comment by andycb** [comment]
The fix was deployed this morning, you should start to see lock events again when turning the thumbturn. Let me know if you have any further issues.

Andy

**Comment by simonepittis** [comment]
I think all works good now :-)
{
    "batteryStatus": 92,
    "connectionStatus": "connected",
    "description": "Main Door Look",
    "firmwareVersion": "2.3",
    "id": "xxxxxx-XXXXXX-xxxxxx-XXXXXX-XXXXXXXXX",
    "lastLockEvent": {
        "eventTime": "2022-05-24T06:34:09.000000Z",
        "eventType": "manualLock"
    },
    "serialNumber": "GLXXX.XXXXXX.XXXX"
}

![image](https://user-images.githubusercontent.com/92569194/169990091-39ec23cf-d00f-46e1-9afd-c23a2f1ee00d.png)

**Comment by andycb** [comment]
Fantastic :)
