### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by tarek86salmi** [GlueHome/homebridge-plugin#24]
ERROR[Hoobs HUb 33F1@Lock Target State] The write handler for the characteristic 'Lock Target State' on the accessory 'Entrédörren ' was slow to respond!

and after the update to the latest firmware version 2.5.0 it stop sending notifications
for manual locking

**Comment by cobch** [comment]
Same problem here. Please find a fix asap.

**Comment by andycb** [comment]
Hi, this looks like an error from Hoobs, rather than from the Homebridge plugin specifically. Can you provide a little more detail on what you're seeing, please? Is this a persistant problem with all operations, or an intermitent issue?
