### ISSUE TITLE
Bluetooth connection status

### ISSUE THREAD

**Issue by VidasTouch** [GlueHome/homebridge-plugin#30]
**Is your feature request related to a problem? Please describe:**
No way to make an automation to auto unlock based on when phone connects via bluetooth to the lock.

**Describe the solution you'd like:**
A way to see if a phone is connected to the lock via bluetooth. A characteristic with bluetooth status info with the value of the bluetooth mac adress from the phone

**Comment by andycb** [comment]
Hi,

Sorry, I’m not sure exactly what you’re asking for here? The phones only connect to the lock as they are preparing to operate the lock, not in the background.  Are you looking for an event on the API to notify when a phone is connected, or am event in the app that can be used to trigger an automation on the device?

The lock is broadcasting a BLE advertisment, that you may be able to use in your projects to know when it is nearby. However we do not have any documentation for customers to work directly with the lock, so I wouldn't be able to help you with interpreting that data.

Andy

**Comment by VidasTouch** [comment]
Hi!

Ok so the phone only connects via bluetooth the second I unlock the door for example? 
I'm looking for a way to auto-unlock based on bluetooth proximity.

**Comment by VidasTouch** [comment]
Hi!

Ok so the phone only connects via bluetooth the second I unlock the door for example? 
I'm looking for a way to auto-unlock based on bluetooth proximity.

**Comment by andycb** [comment]
Correct, the lock tries to spend as little time connected as it can, because it's quite rough on the batteries. If you're comfortable writing your own code, the lock does send out a BLE packet that you can listen for.

If all you want to know if when the lock is close, it's probably easier to just use a Geofence on your device to know when you get home. Remember to keep it really small, though, you don't want to accidentally unlock your door when you don't expect it.

**Comment by VidasTouch** [comment]
Ok, I understand. I’m not very good at coding but I managed to change the ”lock target state” via an Invoke-RestMethod command from powershell to the Homebridge accessory (this plugin). Is it possible to get the BLE packet data with this method as well?

My plan is to start looking for the BLE data when I’m coming home (geo fence) to get a more accurate result.

**Comment by andycb** [comment]
Its not - it would be quite a lot more complicated. If you're using HomeBridge you should be able to do what you need though iOS automations anyway -> When you enter a Geofence, unlock the door.

**Comment by VidasTouch** [comment]
I don’t think it’s good enough to just depend on geofence. What type of approach should I use to accomplish this,  what script language and integration do I need?

**Comment by andycb** [comment]
Sorry, I don't think that's something I can really help you with. If you need more information about the public API or lock, feel free to reach out again here or to support, though.

**Comment by VidasTouch** [comment]
Ok thanks anyway!
