### ISSUE TITLE
Is it possible to easily debug the plugin?

### ISSUE THREAD

**Issue by larsxsamuelsson** [GlueHome/homebridge-plugin#31]
I have run into a strange issue.
The status of the lock is reflected in Home. I get notifications when the status is changed. But every time i try to change the status from the Home app, it immediately goes into "not responding".

The homebridge log is saying nothing at all, so I'm a bit at a loss right now. It doesn't even seem to react when I change status in the app.

Same behaviour on all platforms with the home app. Tried to flushing the cached device on homebridge as well to no avail.

**Comment by andycb** [comment]
Hi, you should be able to debug it using NodeJS on your machine. In theory, you should be able to follow the steps from the template plugin here: https://github.com/homebridge/homebridge-plugin-template

**Comment by larsxsamuelsson** [comment]
Thanks @andycb 
Noticed the error was that i had only given the automation user "resident" and not "owner" when i went from basic auth with my regular user to API-KEY.
Resident was not enough to allow for this to work.
Now everything is back to normal :)
