### ISSUE TITLE
Error message when trying to retrieve api key

### ISSUE THREAD

**Issue by cstickan** [GlueHome/homebridge-plugin#8]
Weh trying to receive the api key via curl i get the following error. Any idea what it means / how it can be avoided?

{"correlationId":"9f259f20","code":50001,"title":"Validation fields error","status":400,"detail":"Validation fields error","instance":"/v1/api-keys","errors":{"cmd":["The cmd field is required."],"$.name":["'0xE2' is an invalid start of a value. Path: $.name | LineNumber: 1 | BytePositionInLine: 12."]}}

**Comment by kafouros** [comment]
Hi @cstickan. Thanks for your feedback. From a first look, it seems there was an issue with the body of the API-Key creation request. 

Can you please ensure that you use characters from the alphabet and/or numbers only as value in the `"name"` attribute when creating the api-key?

Thanks.

**Comment by cstickan** [comment]
Thanks, now its working. However it by default shows all locks connected to my account. Tried narrow it down to just my lock with "lock-id": "432c7f7a-ea53-11e8-9f32-f2801f1b9fd1" but that didnt work. Any optionals that can be used to limit the locks connected?

**Comment by cstickan** [comment]
Thanks, now its working. However it by default shows all locks connected to my account. Tried narrow it down to just my lock with "lock-id": "XXX" but that didnt work. Any optionals that can be used to limit the locks connected?

**Comment by kafouros** [comment]
Hi @cstickan. I see your point. Indeed, the plugin don't support this filtering at the moment, but I will make sure we will add it in the backlog for the next release. Thanks.
